#!/usr/bin/env bash
MESSAGE=${1?Error: no message given}

eval $( echo "yarn build && cp -rf build/ ~/Downloads/App && git checkout master && cp -rf ~/Downloads/App/* . && git add . && git commit -m '$MESSAGE' && git push origin master && git checkout React && rm -rf ~/Downloads/App")